### ISSUE TITLE
Textfields keyboard not appearing

### ISSUE THREAD

**Issue by rosevinod** [honghaoz/AutoKeyboardScrollView#4]
i have added AutoKeyboardScrollView into my xcode Ui interface class instead of UIScrollView
but its not working and when click on texfields keyboard not appearing ...

**Comment by honghaoz** [comment]
Hey @rosevinod Due the limitation of Interface Builder, It won't work if you just simply replace `UIScrollView` with `AutoKeyboardScrollView`. You need to call `handleTextField:` or `handleTextFields:` to manually detecting those textfields.  Please refer the Interface-Builder-Example to see how it works with IB.
